[package]
name = "density"
version = "0.1.2"
authors = ["Kei Tsuji <ktsujister@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
structopt = "0.3"

[profile.release]
lto = true
panic = 'abort'
